[log]
destination = "stdout"
level = "debug"

[defaults]
alert.repeat = "yes" # repeat alert on each cycle
alert.groups = "all" # alert all configured groups
alert.users = "all"


[check.cpu.limit]
pct = 11  # 5 % limit


[check.cpu.loadavg]
min1 = 0
min5 = 4
min15 = 7

[check.filesystem.home]
limit.pct = 30  # alert on 30% usage of /home
alert_every = 5 # send alert on every 5 % increase



# loadavg.15m.limit = 15

[[script]]
path = "/home/user/script.sh" # custom shell script check (returns 2 values, shell output 1/0 and message, ie
# 0, "no issues"
# 1, "error, some error happened"


[[script]]
path = "/opt/check.sh" # more custom checks