[log]
destination = "stdout"
level = "debug"

[defaults]
alert.repeat = "yes" # repeat alert on each cycle
alert.groups = "all" # alert all configured groups
alert.users = "all"
alert.grace.seconds = 60 # wait 60 seconds before sending another alert


[check.cpu]
usage.pct = 1  # 5 % limit

[check.cpu.loadavg]
usage.1m = 0
usage.5m = 2
usage.15m = 9

[check.memory]
usage.pct = 1
usage.size.gb = 200

[check.fs.opt]
path = "/opt"
usage.size.gb = 30

[check.fs.home]
path = "/home"
usage.pct = 20
alert.every = 5

[check.process.kdb]


[check.interface.em1]

[check.network.apache]



[check.script.myscript]
path = "/home/user/myscript.sh"
success.key = 0

[check.script.someother]
path = "/opt/script2.sh"
success.key = "mysuccess"

